### ISSUE TITLE
SerializedGame scores don't include the scores after game's finalization

### ISSUE THREAD

**Issue by Lenetis** [YetAnotherSpieskowcy/Carcassonne-Engine#139]
After the game is finalized, the final score is returned in play turn response, but is not included in SerializedGame (it still has the previous scores, before finalization).

Relevant conversation:
https://github.com/YetAnotherSpieskowcy/Carcassonne-Engine/pull/73#discussion_r1788936005

**Comment by Jackenmen** [comment]
That was an intentional decision - the engine has a separate field with final scores which is filled only on the final turn, while the serialized game contains the points after the turn but without including the calculation of end of game feature scores.
