### ISSUE TITLE
Research of expansions

### ISSUE THREAD

**Issue by Jackenmen** [YetAnotherSpieskowcy/Carcassonne-Engine#4]
Go through the expansions for Carcassonne and determine which of them we may want to consider implementing. This research is supposed to save us from potential massive refactoring in the future due to significant rule changes in some of the expansions.

See Wikicarpedia for the list of expansions:
https://wikicarpedia.com/car/Main_Page

Note that "The Abbot" and "River" are listed as part of the "Base game set" but are actually not part of the first edition which was sold until 2016. These should be researched as expansions as well. *These are also NOT included in Carcassonne tournaments.*

**Comment by BognaLew** [comment]
Selected expansions:

- The Abbot
- River
- Inns & Cathedrals
- Traders & Builders
- Abbey & Mayor
